language: java
dist: trusty
sudo: false
install: true

addons:
  chrome: stable
  apt:
    packages:
      - xvfb
  
jdk:
- oraclejdk8

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 5 # give xvfb some time to start

script:
- mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
