language: java
sudo: false
install: true

jdk:
- oraclejdk8

install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
- mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
