language: java
dist: trusty
sudo: false
install: true

addons:
  chrome: stable
  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &  

jdk:
- oraclejdk8

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5 # give xvfb some time to start

script:
- mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
